################################################################
#
# Annotate.smk configuration file
#
################################################################

# "true/false" flags will add or remove command flags 
# Memory is specified for whole job, in Mb

Annotate:
  
  General:
    #set to "taxonomy" or "function" to run either individually, otherwise set to "both"
    #must be set to "both" to generate annotation report and for full MetaSequencing runs 
    annotation_type: "both"

  Gmt:
    #GMT files will be made for any multimapping features listed, these can be used for set enrichment
    #comma seperated pairs will map the left hand set to the right hand feature
    pairs: "Gene_Ontology_terms:Predicted_protein_name,KEGG_Pathway:Predicted_protein_name,COG_Functional_Category:Predicted_protein_name,KEGG_Module:Predicted_protein_name,BiGG_Reaction:Predicted_protein_name"
    memory: "20000"

    
  ####################
  # Prodigal options
  ####################

  Prodigal:
    memory: "10000"
    threads: "2"
    #additional arguments are appended to the prodigal call
    additional_args: ""

  ############################################################################################
  # Eggnog-Mapper options (Note, run in two stages for speed (seed ortholog then annotation)
  ############################################################################################

  Eggnogmapper:
    #option to specify additional commands that are run before eggnogmapper
    #default settings will load a conda environment that has emapper.py and python2 (default install)
    #this assumes conda is set up in .bashrc (can be set up using conda init bash)
    preload: "set +u; source ~/.bashrc; conda activate metasequencing_py2; set -u"
    #number of ORFs per chunk when chunking for parrallelisation
    chunksize: "100000"
    #command to execute eggnogmapper and location of database files, can be used to direct to custom installs/downlaods and add python2 call to emapper if not using the eggnogmapper conda
    eggexe: "emapper.py"
    eggdata: "/gfs/scratch/eggnog-mapper/"
    #memory and threads for ortholog stage
    memory_orth: "20000"
    threads_orth: "10"
    #memory and threads for annotation stage
    memory_annot: "2000"
    threads_annot: "24"
    #additional arguments passed at the indexing stage
    additional_args_orth: "--temp_dir /gfs/scratch"
    additional_args_annot: ""

  ###################
  # Kraken2 Options
  ###################

  Kraken2:
    #kraken2 command (can use to set to non path installation if necessary)
    krakenexe: "ulimit -v 200000000 && kraken2"
    #database to use for taxonomy assignment 
    db: "/gfs/mirror/kraken2/GTDB_release89"
    threads: "10"
    memory: "150000"
    #additional arguments are appeneded to the call to kraken
    additional_args: ""

  ###################
  # TaxonKit Options
  ###################

  TaxonKit:
    #directory containing NCBI taxdump format data to use with taxonkit (must match ids in the kraken db)
    datadir: "/gfs/mirror/kraken2/GTDB_release89/taxdump"
    #set taxonpre to "True" if the taxonomy used has p__ etc. already in the taxon names (e.g.GTDB dbs)
    taxonpre: "True"

  ##########################################
  # Annotation  merging and report options
  ##########################################

  Merge:
    memory: "10000"

  Report:
    memory: "20000"
