################################################################
#
# Enumerate.smk configuration file
#
################################################################

# "true/false" flags will add or remove command flags 
# Memory is specified for whole job, in Mb

Enumerate:

  General:
    #contig_dir, read_dir, and gtf_dir only need to be set if running the enumerate step alone
    #these set the directories containing the contig fastas, read files and annotation gtfs
    contig_dir: ""
    #set the expected extension after the file name for contigs
    #again only required if running the enumeration step alone
    contig_ext: ""
    gtf_dir: ""
    #features to count from the taxonomic and functional annotations
    feature_list: "kingdom,phylum,class,order,family,genus,species,Predicted_protein_name"
    #features to count combined eg. species + predicted gene name will count genes split by species
    #provide as comma seperated list with pairs split by colons
    feature_pairs: "Predicted_protein_name:species,Predicted_protein_name:genus"
    #GMT files will be made for any multimapping features listed, these can be used for set enrichment
    #comma seperated pairs will map the left hand set to the right hand feature
    gmt_pairs: "Gene_Ontology_terms:Predicted_protein_name,KEGG_Pathway:Predicted_protein_name,COG_Functional_Category:Predicted_protein_name,KEGG_Module:Predicted_protein_name,BiGG_Reaction:Predicted_protein_name"
    #Use multimethod to handle counts when a gene is mapped to multiple annotations of a feature
    #for instance a gene annotated with multiple GO terms.
    #"whole" will add the whole gene count to every annotation, "split" will divide the count across the features
    #this is only important if multimapping features are counted
    #it is instead recommended to count unique features (predicted protein name) and use gmt_pairs to make files for set enrichment
    multimethod: "split"
    
  #################
  # HISAT2 options
  #################
  HISAT2:
    #build settings used for index construction
    build_threads: "10"
    build_memory: "10000"
    #arguments to append to hisat-build call
    build_additional_args: ""
    #settings used for read mapping
    threads: "20"
    memory: "10000"
    #keep unmapped reads
    keep_unmapped: "false"
    #additional paramters to pass to hisat (string appended to call)
    additional_args: ""

  #########################
  # FeatureCounts Options
  ########################
  featureCounts:
    threads: "20"
    memory: "3000"
    #additional arguments appended to the feature counts call
    additional_args: "-p"
    
    
  ##################
  # Script Options
  ##################
  countAnnotations:
    threads: "1"
    memory: "20000"

  combineCounts:
    threads: "1"
    memory: "15000"

  report:
    memory: "20000"
    threads: "10"
