name: metasequencing
channels:
  - bioconda
  - conda-forge
  - r 
dependencies:
  - python=3.6.1
  - snakemake=5.12.3
  - r=3.5.0
  - sortmerna=2.1b
  - seqtk=1.3
  - hisat2=2.1.0
  - samtools=1.9
  - r-ggplot2=3.2.1
  - r-cowplot=1.0.0
  - r-reshape2=1.4.3
  - r-data.table=1.12.*
  - r-stringr
  - r-colorbrewer
  - megahit=1.2.9
  - spades=3.13.0
  - bbmap=38.79
  - prodigal=2.6.3
  - kraken2=2.0.*
  - taxonkit=0.5.0
  - subread=2.0.0
